name: 'camonairflow'

config-version: 2
version: '1.8.2'

profile: 'camonairflow'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

require-dbt-version: [">=1.8.2", "<1.9.0"]

models:
  camonairflow:
    +pre-hook:
        - "{{ check_and_create_audit_log() }}"
    +post-hook:
         - "INSERT INTO audit_log (model, run_at, rows_processed) VALUES (
          '{{ this }}', 
          CURRENT_TIMESTAMP, 
          (SELECT COUNT(*) FROM {{ this }})
          )"
    base: 
      +schema: base
      +materialized: table
      +tags: [base]
    staging:
      +schema: staging
      +materialized: table
    common:
      +schema: common
      +materialized: table
    analysis:
      +materialized: view
      +schema: analysis


snapshots:
  camonairflow:
    path: snapshots
    +tags: snapshot_dependencies
