version: 2

sources:
  - name: raw_csv
    database: testing_dbt
    schema: raw_csvs
    tables:
      - name: crash_data

  - name: gsheets
    database: testing_dbt
    schema: google_sheets
    tables:
      - name: gsheet_finance