name: Continuous Integration

# Trigger this workflow on push or pull_request events
on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  pull_request:
    branches:
      - main  # Runs when creating a pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    services:
      postgres:
        image: postgres:13  # Ensure you are using the correct version
        ports:
          - 5433:5433     # Expose the default PostgreSQL port
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing_dbt
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # or whatever version you use

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      - name: Set up DBT profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          default:
            outputs:
              astro_dev:
                type: postgres
                host: localhost
                port: 5433
                user: ${{ secrets.DBT_PG_USER }}
                pass: ${{ secrets.DBT_PG_PASS }}
                dbname: ${{ secrets.DBT_PG_DB }}t
                schema: public
                threads: 2
            target: astro_dev
          EOF
      
      # Step 5: Install DBT package dependencies
      - name: Install DBT dependencies
        run: |
          cd dbt && dbt deps

      - name: Run DBT build
        run: cd dbt && dbt build 