name: Continuous Integration

# Trigger this workflow on push or pull_request events
on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  pull_request:
    branches:
      - main  # Runs when creating a pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Change directory to DBT project
        run: cd dbt

      # Step 6: Run DBT build (this combines dbt run and dbt test)
      - name: Run DBT build
        run: dbt build          