name: Scheduled Charging Distance Update

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7am UTC (5pm Melbourne time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-charging-distance:
    runs-on: ubuntu-latest

    env:
      OPENROUTESERVICE_API_KEY: ${{ secrets.OPENROUTESERVICE_API_KEY }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Check API Key
        run: |
          if [ -z "$OPENROUTESERVICE_API_KEY" ]; then
            echo "ERROR: API key is not set!"
            exit 1
          else
            echo "API key is available to the workflow ✓"
          fi

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DBT profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          camonairflow:
            outputs:
              dev:
                type: duckdb
                path: ${{ secrets.MOTHERDUCK }}
                schema: public
                threads: 2
                extensions:
                  - httpfs
                  - parquet
                  - motherduck
            target: dev
          EOF

      - name: Install DBT packages
        run: cd dbt && dbt deps

      - name: Run Charging Distance Model
        run: |
          cd dbt
          echo "Running charging distance model build"
          dbt build --select base_open_charge_driving_distance+
